name:  GitHub Actions Demo
run-name:  ${{ github.actor }} is testing out GitHub Actions
on:
  push:
    branches:
      - main
permissions:
  id-token: write
jobs:
  oidc:
    runs-on: ubuntu-latest
    steps:
    - name: Install OIDC Client from Core Package
      run: npm install @actions/core@1.6.0 @actions/http-client
    - name: Get Id Token
      uses: actions/github-script@v7
      id: idtoken
      with:
        debug: true
        script: |
          const coredemo = require('@actions/core')
          let id_token = await coredemo.getIDToken()
          coredemo.setOutput('id_token', id_token)
    - name: Decode Id Token
      uses: actions/github-script@v7
      with: 
        script: |
          console.log('TO READ')
          const token = ${{ steps.idtoken.outputs.id_token }}
          console.log('TOKEN READ')
          const arrayToken = token.split('.');
          console.log('ARRAY TOKEN', arrayToken)
          const tokenPayload = JSON.parse(atob(arrayToken[1]));
          console.log(tokenPayload)
